---
services:
  reverse-proxy:
    container_name: reverse-proxy
    cpus: 1.0
    image: nginx:latest
    mem_limit: 1024m
    networks:
      - reverse-proxy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/ssl            # Self-signed certificates
    # - /etc/letsencrypt:/etc/nginx/ssl   # For use with cerbot, certs at /etc/nginx/ssl/live/<domain>

networks:
  reverse-proxy:
    name: reverse-proxy
    external: true
